### ISSUE TITLE
MEM 1.8 - Removing ME3 null MIPs

### ISSUE THREAD

**Issue by CreeperLava** [MassEffectModder/MassEffectModder#1]
Here is an error I get each time I try to remove ME3 null MIPs :
![masseffectmodder_2016-11-26_16-48-16](https://cloud.githubusercontent.com/assets/12874678/20641451/49fb97fc-b3f8-11e6-8d24-35061c3db618.png)
No issue with ME1, haven't tried ME2 yet.

Log :
http://pastebin.ca/3742494

There shouldn't be any TOC.bin file in __metadata, so why is MEM searching there ?

**Comment by aquadran** [comment]
good question, if you have __metadata sounds like you don't have DLC unpacked? It seems check is no longer valid if DLC is packed or not.

**Comment by aquadran** [comment]
Uploaded v1.9 which have more checks. It will get DLC files which starts with DLC_ just in case. Not sure if it's fine. Also check if directory is "empty" like "__metadata".
I'm not sure what state is for your DLC directory, if you don't unpacked, but tool should detect pcc files in it. or you had already unpacked by ME3x and it left "__metadata" directory.
Or you had vanilla packed adn mod DLCs unpacked before unpack DLCs.

**Comment by CreeperLava** [comment]
I did unpack the DLCs, but with ME3Explorer, not MEM. Not that it should change anything.

**Comment by aquadran** [comment]
Ok, please try 1.9 version then. I just re-uploaded binaries.

**Comment by CreeperLava** [comment]
I'm happy to report that it works, now !

So the _metadata folder is unneeded ? If I can remove it safely, I see no reason to keep it then :).

**Comment by aquadran** [comment]
_metadata contains some post installer info, but it's not used by game.
