### ISSUE TITLE
Crashs after generate game map

### ISSUE THREAD

**Issue by DunKalevra** [MassEffectModder/MassEffectModder#14]
I'm playing ME3 and it crashed right before the beginning of Priority: Eden Prime, so I restore to vanilla and tried again, the mission started with no problem, so I proceed to apply the DLC mods (Interface Mods and one hair mod), again it was fine, then tried to apply ALOT ME3 and crashed, so I played this mission without it and applied after it was over.
After applying the textures I did some missions and everything was fine, until I tried to do N7: Cerberus Fighter Base, the game crashed right after the beginning of the mission, so I restored to vanilla and the mission started without problem, applied the DLC mods and no problem, then I tested just generate the game map and it crashed.
Even after I apply ALOT ME3 the game still crashs.
Can it be that the step that generate the game map and remove empty textures somehow is modifying some archive that leads to the crash?

**Comment by aquadran** [comment]
yes, I find out today that scan and remove break data. I'm working on fix it.

**Comment by aquadran** [comment]
try 1.80 release

**Comment by DunKalevra** [comment]
Still have the issue. Tried complete vanilla without mods and it loads, then I generate the game map and tried again and it crashs.

**Comment by aquadran** [comment]
ok, one issue fixed, but I can confirm there is another one which I found using one of my savegames for me3. I didn't check this save recently, but also it was not so long ago :) so it should take me long to find when I broke it.

**Comment by aquadran** [comment]
please use 1.69 version from release downloads for now until I fix it.

**Comment by DunKalevra** [comment]
Thanks, 1.69 is working even after removing empty mipmaps.

**Comment by aquadran** [comment]
can you try 1.81?

**Comment by DunKalevra** [comment]
No problems with 1.81, thanks for the updates.
