### ISSUE TITLE
language:Files ME3

### ISSUE THREAD

**Issue by reh8231** [MassEffectModder/MassEffectModder#16]
language:Files....really like the MassEffectModder, i was having problems with it running , language files was the problem, i made i new clean install of game and installed some DLC mods. went through all the DLC mods and deleted all language files and kept only  (INT) files, and in Mass Effect 3\BIOGame\CookedPCConsole folder deleted all language files and only kept  (INT) language files, deleted  (DEU)
(ITA)
 (FRA)
 (ESN)
(POL)
 (RUS) ...now MassEffectModder unpacks dlc with dlc mods installed and runs the scan tree with no problems......the other language files was giving out of bound errors and stuff....even without dlc mods just the game non moded at all i had problems with language files in Mass Effect 3\BIOGame\CookedPCConsole folder.......don't know if this info is useful or not... just thought i would pass it along.....thank you for MassEffectModder.

eddie

**Comment by aquadran** [comment]
languages are working fine. check your game data using option from menu.
