### ISSUE TITLE
TPFs containing duplicate textures in multiple formats fails to convert

### ISSUE THREAD

**Issue by sialivi** [MassEffectModder/MassEffectModder#17]
I was trying to do a .tpf to .mem conversion with version 1.91 and it failed with an error message that one of the files wasn't ATI2. I informed the author of the mod in question and got the following response:

> This probably is because I package the normal as both a DXT5 for Texmod and an ATI2N for ME3Explorer. Texmod ignores ATI2N, so to be compatible with both tools I have to add it twice. ME3Explorer loads the first (ATI2N) and collapses the second entry (DXT5) automatically and ignores it, so it never complains about the format and doesn't require fixing.. It's automatically handled. If MEM doesn't deal with duplicates the same (or at all) it makes sense this would trigger issues.

**Comment by aquadran** [comment]
thanks for information, I wasn't aware of such cases. I guess it's not a problem in the end now, MEM should only convert texture with the same format, and ignore which not match. in the future MEM will auto fix them, I should take care of this too. Thanks
