### ISSUE TITLE
MD5 Hash fail at fresh installed version

### ISSUE THREAD

**Issue by jokoho48** [MassEffectModder/MassEffectModder#19]
After 2 reinstalls the MD5 Hash test still fails. I am not sure but my current idea would be that the md5 hashes are different if you use a different language.

i use german as language.

http://pastebin.com/3kh7w210

**Comment by aquadran** [comment]
md5 sums are against all languages versions provided by Origin.

**Comment by jokoho48** [comment]
than this is wierd. because i got a totaly fresh download. and all 3 games have the same issue

**Comment by aquadran** [comment]
ok, I'll try look into, strange but no one else mention this before

**Comment by jokoho48** [comment]
i am open for every information request if you want

**Comment by aquadran** [comment]
I just installed german version from Origin. No issues with md5 sums, before unpack DLCs or after.

**Comment by jokoho48** [comment]
ok after the 3rd reinstall it worked. with the newst version
