### ISSUE TITLE
Unhandled exception in .Net Framework while building the tree ME2 Texture Explorer

### ISSUE THREAD

**Issue by Thommaal** [MassEffectModder/MassEffectModder#2]
- Vanilla Mass Effect 2, data integrity verified in Steam after the error appeared for the first time, game re-installed when the error re-appeared.

- DLCs (13 in number) installed: DLC_CER_02; DLC_CER_Arc; DLC_EXP_Part01; DLC_EXP_Part02; DLC_HEN_MT; DLC_HEN_VT; DLC_MCR_01; DLC_MCR_03; DLC_PRE_Cerberus; DLC_PRE_Collectors; DLC_PRE_Incisor; DLC_PRO_Gulp01; DLC_PRO_Pepper01; DLC_PRO_Pepper02; DLC_UNC_Hammer01; DLC_UNC_Moment01; DLC_UNC_Pack01.

- .Net Framework installation (v4.6x) checked.

- OS: Windows 10 64bit.

Error:
![masseffectmodder_issue02](https://cloud.githubusercontent.com/assets/24566859/21186545/5563aa28-c215-11e6-904f-f7ec5d8453a8.png)

Detailed error message:
`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Exception: Exception of type 'System.Exception' was thrown.
   at StreamHelpers.StreamHelpers.ReadToBuffer(Stream stream, Int32 count) in c:\stuff\MassEffectModder\Helpers\StreamHelpers\StreamIO.cs:line 34
   at MassEffectModder.Texture.getMipMapData(MipMap mipmap) in c:\stuff\MassEffectModder\MassEffectModder\Texture.cs:line 415
   at MassEffectModder.Texture.getImageData() in c:\stuff\MassEffectModder\MassEffectModder\Texture.cs:line 367
   at MassEffectModder.TexExplorer.FindTextures(String packagePath) in c:\stuff\MassEffectModder\MassEffectModder\TexExplorerTree.cs:line 226
   at MassEffectModder.TexExplorer.PrepareListOfTextures() in c:\stuff\MassEffectModder\MassEffectModder\TexExplorerTree.cs:line 86
   at MassEffectModder.TexExplorer.Run() in c:\stuff\MassEffectModder\MassEffectModder\TexExplorer.cs:line 139
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
MassEffectModder
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///H:/Aleph/ME3/Werkzeuge/MassEffectModder/MassEffectModder.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
StreamHelpers
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///H:/Aleph/ME3/Werkzeuge/MassEffectModder/StreamHelpers.DLL
----------------------------------------
LZO2Helper
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///H:/Aleph/ME3/Werkzeuge/MassEffectModder/LZO2Helper.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
`

**Comment by Thommaal** [comment]
sorry, 17 DLCs

**Comment by aquadran** [comment]
English version of game, right?

**Comment by Thommaal** [comment]
Yes; the same goes for the DLCs, of course. 

One additional information: On my first try, the package count went to around 1700 before the error appeared. After the re-install, the count went beyond that limit, but not far enough, obviously, and it always gets stuck at the same place.

I ponder to uninstall all DLCs, and try to build the tree again.

**Comment by Thommaal** [comment]
The problematic data is NOT in the base game. But how do I build a new tree, when I add the DLCs one by one to find the problematic one?

**Comment by aquadran** [comment]
no need, I'll put special version which print package and texture name.
https://www.dropbox.com/s/5a2kf9l8wg9xf44/MassEffectModder-test1.zip?dl=0

**Comment by Thommaal** [comment]
Ah, nice. And I had just found out that the problem occurs only when "Zaeed - The Price of Revenge"	(DLC_HEN_VT) is installed.

**Comment by Thommaal** [comment]
I case, you wonder, yes, the DLC is legal. But it might have become corrupted. If you own the English DLC too, here is my MD5-hash: 6C26E31293B126D276F00453DCCCD13E

Your test software indicates teat the problem is the following file:

![masseffectmodder_issue03](https://cloud.githubusercontent.com/assets/24566859/21194871/d519b82c-c231-11e6-9fbd-598ea61729e0.png)

**Comment by aquadran** [comment]
I have MD5 (BioD_OmgHub_DLC_Veteran.pcc) = c0ca013894fc134915c7b8897ed5857b. file size: 1651128. what is filesize for you file?

**Comment by Thommaal** [comment]
And there we seem to have identified the problem; my hash is: 3EA7316A07D64CB08C5399BF4ED0949C

File size: 3,722,459 bytes

**Comment by aquadran** [comment]
is DLC from Steam or from instalation package?

**Comment by Thommaal** [comment]
It's an installation package - I have just gone to social.bioware.com to download it again under my Registered Game Content. Am I glad that the site is still up and running ..

**Comment by aquadran** [comment]
I have local backup just in case site goes down. I have DLCs from there too. I wonder about file size, it's not data corruption. mine is about half size smaller

**Comment by Thommaal** [comment]
No, it's not data corruption; the hashes of my old DLC and the new downloaded one are identical; I am still going to install the new one, just in case something went wrong during installaion ..

**Comment by aquadran** [comment]
MD5 (ME2_Zaeed.exe) = 6c26e31293b126d276f00453dcccd13e file size: 522,684,080

**Comment by Thommaal** [comment]
Okay, it looks like something wnet wrong during installation of the DLC. This time, it worked without a hitch: all 3258 textures are accounted for. Now I am going to try out your software. :) Thank you for your help. I think, the issue can be closed.

**Comment by aquadran** [comment]
ok, then, great :)
