### ISSUE TITLE
updateGfxME dont use correct gameId. it allways use MeType.ME1_TYPE

### ISSUE THREAD

**Issue by jokoho48** [MassEffectModder/MassEffectModder#20]
refs: 
https://github.com/MassEffectModder/MassEffectModder/blob/master/MassEffectModder/MainWindow.cs#L526
https://github.com/MassEffectModder/MassEffectModder/blob/master/MassEffectModder/MainWindow.cs#L532

**Comment by aquadran** [comment]
you are right

**Comment by aquadran** [comment]
copy and paste bug

**Comment by jokoho48** [comment]
i open a PullRequest. feel free to merge #22

**Comment by aquadran** [comment]
too late :)

**Comment by aquadran** [comment]
thanks anyway
