### ISSUE TITLE
Main Installer Window doesn't show

### ISSUE THREAD

**Issue by lozneo** [MassEffectModder/MassEffectModder#23]
Hello. I am trying to use MEM to install ALOT for Mass Effect 2. My issue is that the main installer window does not show - the window with the pre-installer checks and so on. I have tried running it as admin, I have tried running it normally, I've tried using it in a different location but no luck - the main installer window refuses to show and I'm stuck with the main window. Is there a way to fix this? Please advise.

I am running MEM 1.103 on Windows 10 Professional 64bit. Mass Effect 2 is installed through Steam on my F drive (which is not my Windows install drive).

**Comment by aquadran** [comment]
you need to run MEM from ALOT directory. you should have also installer.ini file there.

**Comment by lozneo** [comment]
Thanks for prompt response. When I downloaded the updated MEM, there was no installer.ini. Is there somewhere I can get this from? Thanks.

**Comment by aquadran** [comment]
you need copy updated MEM to ALOT folder to overide old one. there should be installer.ini

**Comment by lozneo** [comment]
There is no old MEM or old ALOT to override. This is a fresh install. I have the ALOT files extracted in the MEM folder and there is no installer.ini. Please advise where I can get this from.

**Comment by CreeperLava** [comment]
There is a picture tutorial to make things easier, you should follow it :).

**Comment by lozneo** [comment]
I have followed the tutorial but it doesn't work for me. I've extracted the main file and the update to the same directory as MEM.exe; since my ME2 is through Steam (and I turn Steam so it doesn't mess with the files) I don't need to turn off Origin auto-update; I then click open on MEM and the Main Installer Window does NOT show. As has been established, installer.ini is missing and I do not have a copy of it. This appears to be causing the issue. Can someone please advise where I can get this from?

**Comment by CreeperLava** [comment]
The installer.ini is in any of the main ALOT downloads.

**Comment by lozneo** [comment]
Thank you very much for answering this question. MEM is now working as intended.
