### ISSUE TITLE
Error message when installing ALOT for ME3

### ISSUE THREAD

**Issue by Fatski** [MassEffectModder/MassEffectModder#25]
Whenever I try to install ALOT to ME3 I get this annoying message saying "Access to path (insert path) denied". I don't know how to fix it, I've tried just reinstalling and trying again. I've searched for fixes but I can't find anyone with the same problem. 
I get two options. One is to continue installing and the other is to exit the application. The thing is, if you press continue it doesn't keep installing. It just gets stuck on whatever precentage it was at when the error occured.
Please help, thx!

**Comment by aquadran** [comment]
Check directory access to game folder. I could try help you if you provide more info.
