### ISSUE TITLE
ME1 Textures not rendering at full lod in game.

### ISSUE THREAD

**Issue by CDAMJC** [MassEffectModder/MassEffectModder#26]
Hello,

I am trying to convert all MEUITM textures over to MEM. So far so good. It fixes many issues, maybe all issues I had from ME3Explorer. I am running into one pretty big issue though (probably something I'm doing wrong).  

I am creating mem files from the .tpfs, obviously 2 don't work because I changed the formats (film grain and lightmaps) no biggie there. But the rest all install and when I check the file info etc...they are the right size, formats, mip maps all looks good. 

However, when I load the game no textures seem to be rendering at full LOD. I think it must be a lod/mip issue as I can see the textures are installed properly when I check the info.  I just can't figure out how to fix it. I tried remove unused mips and update lod settings multiple times, nothing changed.
 
Have you run into or noticed this? It was easy for me to miss at first, but up close camera shots really show the lower res textures, in particular Udina's outfit and Avina. They almost look back to vanilla LOD but I can see the extra shading from my textures so I feel like it's just a low LOD issue. I can see it on almost all textures I installed though, nothing seems to be getting to 4k or even 2k when the source textures are those resolutions. I ran the game at all the way up to 5K resolution to ensure the highest mips should be loading but no luck.
 
Any help/advice would be super appreciated.  

Alos, thank you for creating this great tool.  It fixes issues I have been trying to work around for 4 years :D

**Comment by aquadran** [comment]
Hi CDAMJC

Very nice you found this tool usefull :)
I found lightmaps are still better to use after conversion to original texture format.
Of course not so great as rgb32 :)
What was issue with filmgrain texture format?
I have it converted, but I'm not sure what was a diffrence.
Personally I use filmgrain in shaders.

Regarding LOD issue. I'm not sure if this a case since you mention no textures are rendered at higher resolution. For some small number of textures engine refuse render at higher mipmaps for specific mipmaps layaout. It's not just ME1, it's particular for all series. I have solution for this, but I didn't figured out how to filter them all yet. For now I can add exceptions, like Garrus face.

Can you check more textures? This is sounds like not possible to me :D

**Comment by CDAMJC** [comment]
Thank you for the reply,

I had film grain and the lightmaps in uncompressed dds format A8R8G8B8 or something along those lines, from a long time ago when using TexMod.  I will play around with DXT in the future with those, but again I consider them very minor to the mod which is why I've left them be for so long.

For now I am learning a bit thanks to your explanation and some info I received from CreeperLava.  Before this I always believed the Bioengine.ini texture settings didn't do much with modded textures, but apparently that's because ME3Explorer converted them all to lightandshadowmap format, while I was tweaking character diff spec and norm (no wonder I saw no difference).  

So I will try from scratch just to make sure everything is fresh and proper.

I will mention some observations now in case you want to look into them immediately. But I will get more specific and extensive when I have some time, perhaps this weekend.  For now here are my general observations:

There are ver low LOD issues with Avina, Udina's clothing.  The female scalp when bald, there is some black artifacting along the forehead, and also female hairs in general seem to be not in full res both on the diff and the mask.  The female faces or perhaps just the normal maps, but something is causing a seam that is non existent at full lod.  The N7 Armor appears capped at 1024 along with Anderson's uniform.  At least in some of the cut scenes where the camera gets close, it's pretty noticeable.  

Again, I will run more extensive tests to make sure, and as I go I will make a list with the actual file names so hopefully it will be more helpful.  I also think I will log the textures with Texmod to see exactly what resolution is being loaded and make note rather than speculating.  This will probably take quite some time but hopefully it will be helpful.

Thanks again for creating and sharing this tool, in most (all but one) ways it surpasses ME3Explorer for ME1 textures (what I am most interested in :))  Also it's so fast!  Much easier to test and mod.

**Comment by aquadran** [comment]
"I will play around with DXT in the future with those, but again I consider them very minor to the mod". Difference is big even with DXT1.
I'll take a look into LOD issues. I have special texture which render information which actually is used.

**Comment by CreeperLava** [comment]
@CDAMJC Did you notice an improvement when changing lightmaps ? I tried modifiying some in ME3, but even extreme changes like an entirely black or white texture didn't change anything in-game.
Also, if you do want to save these ARGB textures in DXT1, try using Intel's DDS plugin for PS. It has pretty good compression quality and should avoid posterization.

**Comment by aquadran** [comment]
@CreeperLava in ME1 it's diffrent thing. I'll provide screenshots to compare

@CDAMJC I fixed issues in MEM 1.112, it turns out it was lod settings. Probably engine bug. min lod is interpreted as max. So you need only update lod settings from MEM menu.

**Comment by CDAMJC** [comment]
Thank you I will test this weekend!

**Comment by aquadran** [comment]
how results?

**Comment by CDAMJC** [comment]
Sorry for the delay testing now will get back soon.

**Comment by CDAMJC** [comment]
Well, I've waited 5 years for a proper mip map fix and you did it!  Thank you so much.  I have been busy with contract texture work, full time work family etc... and other mods, but now I think I will make more time for modding Mass Effect.  Now that these issues are gone, thanks to you, I feel comfortable updating and adding content.  I worked perfect and it's so fast!  I am so excited, thank you again for all your work and creating this great tool!

**Comment by aquadran** [comment]
I don't know if you are aware of installer mode of MEM. Take a look how ALOT for ME2/ME3 is done.
MEM detect installer.ini file. If present it run in installer mode and process is fully automated. Two button process: http://imgur.com/a/Wdsiq  
I will add option in installer.ini file to support tittle name of installer. By default now it's for ALOT.

**Comment by aquadran** [comment]
btw. MEM applying LAA for ME1 automatically and few proven gfx configuration options.

**Comment by aquadran** [comment]
just added option for installer.ini file, so it will looks like this:
[Main]
GameId=ME1
BaseModName=MEUITM

**Comment by CDAMJC** [comment]
This is all great thank you so much! I will get to work trying all this in
the next few weekends.
