### ISSUE TITLE
Won't convert some dds to mod

### ISSUE THREAD

**Issue by violetaz** [MassEffectModder/MassEffectModder#28]
![mod](https://cloud.githubusercontent.com/assets/28888746/26342816/236639b0-3f5f-11e7-998c-f144dfdd8708.png)

Screenshot attached, won't let me attach dds files.
Whenever I try to convert the dds files from the TRAM mod for Mass Effect 2 (any part of it, though this shot is specifically from the Miranda > Primary Miranda folder), this error occurs. I am not sure why, or if it's just somehow an incompatibility between the mods? Or if it's just because TRAM was made for use with ME2Explorer? Any help appreciated.

**Comment by aquadran** [comment]
as error prompt. files needs crc/hash in file as in error message.
