### ISSUE TITLE
Can't get mods to install properly on language localization re-packs, example R.G. Mechanics

### ISSUE THREAD

**Issue by CDAMJC** [MassEffectModder/MassEffectModder#29]
Hello,

I am having great success with MEM when working directly from the Origin and Steam versions, however I have a R.G. Mechanics localization which was given to me so I could make the mod compatible with Russian and Polish language users (these are the original fans of MEUITM in the early days).  

With this localized version I get a large error list generation when building the file tree. When I attempt to install the MEM files many of the mods simply yield black textures. I figure it's because the game has been re-packed with addition language files and is therefore not "original".  However the textures are all vanilla. 

Is there a way to force the installs over a repacked game?  Before I release the MEM version of MEUITM I want to be able to appease these users as they currently have support with the ME3Explorer built version.

Any help would be greatly appreciated, I know there is also a Brazilian localization and more so I'm guessing this would be useful for all languages not originally supported by Bioware/EA who want to mod the game with MEM.

As always thank you for this wonderful tool :)

**Comment by aquadran** [comment]
Polish language version (voice and text) had official DVD release and it's compatible, and MEM in general is compatible with any mod if game data is not broken. I'm not familiar with R.G. Mechanics localisation, so no idea, but based what you said it's quite broken. So I'm afraid I can not do much more. There are two other mods which has similiar rate of broken game data: controller mod and faster elevators mods.

You may think ME3Explorer works with that, but it's not :) It's like hidding issues.
MEM is more engine friendly than ME3Explorer and trying more in precise replace textures.
So it take care more about game data, and how it works depend on proper game resources.
What you see, errors which most like textures entries which points to wrong places in game data. How I suppose to work with that? MEM tries skip such entries in scan, however results depends how much broken it is. And I don't support repacked games in general.

Now refering to above two mods, errors are not in just non-important textures, but also in important textures. So I flagged mods as not compatible until mods authors fix them.

btw. I'm available on ALOT discord channel: https://discord.gg/gwK7fPV

**Comment by aquadran** [comment]
try 141. it has fix for ME1 pcc mods. possible it may fix that too. it was bug in MEM after :)

**Comment by CDAMJC** [comment]
Works perfectly!!! Thank you so much!
