### ISSUE TITLE
newest version ?

### ISSUE THREAD

**Issue by thunderpants** [MassEffectModder/MassEffectModder#31]
I have a copy of this on my hard drive named :
MassEffectModder-v1.90.zip

I think i downloaded it in Feb.2017 (not  sure as memory not great but the rar file is dated 2nd feb.2017)

The version posted here on Github is called :
MassEffectModder-v140.7z

How come i seem to have an older copy with a higher version number ?

**Comment by aquadran** [comment]
1.90 is like 90. I drop "1."

**Comment by thunderpants** [comment]
ok thanks .
