### ISSUE TITLE
[ME1] Crash during removal of mip maps 

### ISSUE THREAD

**Issue by StoneboyCZ** [MassEffectModder/MassEffectModder#32]
I have the fresh install of the Mass Effect 1 (Origin). When I click on Texture Manager button, LAA flag is set and then the scanning begins. I´m using the newest version (154) and MEM always crashes during the removal of mip maps. One of the previous versions (148?) worked fine. 

I tried using Steam version (fully patched with 2 dlcs), same problem.

Update: Just tested it again, MEM crashes at BIOC_Materials.u . 
Details: 
Unhandled exception at 0x00007FFEF6F4775F (ntdll.dll) in MassEffectModder.exe: 0xC0000374: A heap has been corrupted (parameters: 0x00007FFEF6FA86B0). occurred. Problem seems to be with lzo2wrapper.dll  according to stack trace.

Windows 10 Pro 1703, build 15063.540

Update 2: Just tried it again. The problem persists, but with the different file. After reinstalling ME1, the problem manifests again with  BIOC_Materials.u.

**Comment by aquadran** [comment]
fixed in 155

**Comment by StoneboyCZ** [comment]
Thanks, it works :).
