### ISSUE TITLE
LOD settings

### ISSUE THREAD

**Issue by roivas** [MassEffectModder/MassEffectModder#33]
Hi

Not really an issue but I got some trouble with MEM ^^;

I'm a new MEM user & for now I use it with MEUITM. I used to play ME1 with the .exe version of MEUITM for years but now I'm trying it with MEM since the author recommanded to try.

And it work pretty well! But I've noticed that I've now an issue I've never encountred with the .exe version.

I've noticed that when a CS or a battle is going to happen I've huges fps drop for like 0.5 to 1 sec.
I've tried to find  why. (I've 0 skill in modding  ^^; ) 

I followed every step of you MEM user guide. At the end of your guide you explain that we have to update LOD setting so textures mods work properly.

But then I saw that the setting you show on your guide are not the same that are applied by MEM in bioengine .ini. In bioengine.ini, all "MinLODSize" are set to 4096 and I'm not sure that it's normal since the guide have different values. 

I've changed the value in bioengine.ini so they are the same as in the guide & I've no more trouble with the game (I've even tried to set them all to 2048 and it works fine too). 

So I wanted to know if the LOD setting applied by MEM is correct and if yes, if I might have done something wrong with MEM that could explain my problem or if there is something I can do so I don't have fps drops (that never occured with MEUITM in is .exe version). 
I think it's related to the texture loading but I'm not sure, 
The game is installed on a SSD (tried with a normal hard drive before & same problem), i'm using windows 10 64 bit, intel i7 6700k, Titan X ,16go ddr4 and plyaing in 4k.

Excuse my english & my really noob questions ^^;

Thx agin for your work!

**Comment by aquadran** [comment]
Hi,

The guide has old outdated values which was wrong not becouse they were wrong, but game engine has bug. So later time I correct them to values which actually make LOD settings effect in game.
Regarding frames drop it might be related to because game engine is old and might not work as fast with a new bigger textures. MEUITM exe version is based on very early version of ME3Explorer which did things differently.
