### ISSUE TITLE
Rendering thread exception

### ISSUE THREAD

**Issue by roivas** [MassEffectModder/MassEffectModder#35]
Hi, sorry to bother you again.

Since the last Origin &/or windows 10 update, I've an error everytime I try to make ME 1 works.
Last time I told you I had some fps issue but the game was working  with mem + lod setting.

Then it stopped to work (I changed nothing to the game & the automatic update is off).

So I tried a clean install of ME1 but if I use "update lod setting" from mem I'll have this message everytime, even vanilla.

Thx again for your help.

<img width="1920" alt="me1crash" src="https://user-images.githubusercontent.com/32177242/31186656-8a4bcf66-a92f-11e7-9648-887b5e51a21f.png">

**Comment by aquadran** [comment]
for vanilla you need remove lod settings. you can use option from MEM menu.

**Comment by roivas** [comment]
the problem is the message is the same if the game is modded ^^.  Modded of unmodded i got this message.

**Comment by roivas** [comment]
To be clear (since my english is not really good, sorry T.T).
- I had the game + MEUITM + METSR1 installed with MEM 1.60 + lod setting. It woked perfeclty
- Then I got an Origin or Windows 10 update & this error message poped when I tried to play. 
- So, I tried a clean install of the game with MEUITM & METSR1 + lod setting with MEM 1.62: same error message again.
- I tried the game + meuitm + metsr1 with MEM but without lod setting: it works.
- I was curious so I tried a new clean install & just applied lod setting without any mod just to see what would happen: same error message again.
- Then I tried clean install + meuitm + mem 1.62 + lod setting: same error message.
- clean install + METSR1 + mem 1.62 + lod setting same error message

Actually  I'm playing the game with MEUITM + METSR1 installed with MEM 1.62 but I changed manually the bioengin.ini lines with recommanded parameters from c3anderson only way i can make it work for now.

**Comment by aquadran** [comment]
you can not use lod settings on vanilla game, it will crash as you reported.

**Comment by roivas** [comment]
I understand it'll not work with vanilla. But as I said it's not working with MEUITM &/or METSR1 either. It's something new since it workied before.

**Comment by aquadran** [comment]
what you mean by MEUITM installed? what source?

**Comment by roivas** [comment]
meuitm tpf version converted with your tool in mem

**Comment by aquadran** [comment]
I just tried, I don't get this issue.

**Comment by roivas** [comment]
Well i don't know then. The only difference between when it worked & when it stopped is an origin & w10 update. I did nothing else :/. 
thx for your time T.T

**Comment by aquadran** [comment]
btw. I suggest use ALOT for ME1.

**Comment by roivas** [comment]
Thx for your suggestion.  I tried a lot + update + addon (meuitm) with a clean install of me1. Mod Install is fine, but again it only work if I don't apply lod setting with mem, otherwise, same message error.
