### ISSUE TITLE
System.Exception thrown

### ISSUE THREAD

**Issue by ChaimPotok** [MassEffectModder/MassEffectModder#36]
Running as Admin on a folder in the Desktop.

Returns with 

`Exception of type 'System.Exception' was thrown`

Log as [Pastebin](https://pastebin.com/hWZfNa1u)

Log in .txt format:

[mem error.txt](https://github.com/MassEffectModder/MassEffectModder/files/1545125/mem.error.txt)

**Comment by aquadran** [comment]
Works fine here. I need more information how to reproduce this issue.

**Comment by ChaimPotok** [comment]
Here's everything I can think of. Tell me if you need anything specific.

Windows 10 ver.1709
Fresh install straight from the Github. Using checked ALOT files I've used previously.

Video of reproduction, also showing files' locations:
[1.zip](https://github.com/MassEffectModder/MassEffectModder/files/1545217/1.zip)

My PC specs:
[specs.txt](https://github.com/MassEffectModder/MassEffectModder/files/1545223/specs.txt)

**Comment by ChaimPotok** [comment]
Fixed it.

Moved my Mass Effect folder outside of steamapps/common folder, applied ALOT, then moved it back.

**Comment by aquadran** [comment]
I tried the similiar thing. I have Origin version, but I moved game to Steam (e:\Games\SteamLibrary\SteamApps\common\) 
No issue here.
Maybe external antivirus or game data too deep in folders?

**Comment by aquadran** [comment]
game path can not be more than about 180 chars.
