### ISSUE TITLE
option to pack w/o compression

### ISSUE THREAD

**Issue by Artofeel** [MassEffectModder/MassEffectModder#38]
since I don't like when game data is compressed, I believe game run more smoothly when no compression is used (especially on the old ME1 engine)
can you add option to mod game data without LZO compression?
or maybe just don't use modified(?) version of LZO, because right now [Unreal Package Decompressor](http://www.gildor.org/down/43/umodel/decompress.zip) can't decompress files made by MassEffectModder

also, .mem files compressed with deflate which is worse than LZMA
any modder shares it's mods with 7z anyway and compressed (with deflate) data can't be compressed better with LZMA
so is better to remove compression of .mem files at all

**Comment by aquadran** [comment]
uncompressed game will take a lot of space, several times more, so sorry but no.
LZO is not modified in MEM and engine accept it, so how it would be modified? So pointed tool need to be fixed.

.mem files are designed to be CPU usage and multithreading friendly. so again but no.

**Comment by Artofeel** [comment]
> uncompressed game will take a lot of space, several times more
>
actually just x1,5x-x2 more
>LZO is not modified
>
it is
then way program that designed to uncompress any of Unreal Engine Game packages, can't decompress MEM data?
maybe you use wrong lib?
just point me what I need to change in source at least
>.mem files are designed to be CPU usage
>
they should be designed for sharing...

**Comment by aquadran** [comment]
"actually just x1,5x-x2 more" no, you ignore textures. they are compressed too.

"then way program that designed to uncompress any of Unreal Engine Game packages"
it seems not if can't handle packages and engine can.

"they should be designed for sharing..." 
write own software, then you can define what should be and what not.
