### ISSUE TITLE
Mass Effect 2 - Installation from original DVDs, MEM-crash without added DLC

### ISSUE THREAD

**Issue by Thommaal** [MassEffectModder/MassEffectModder#4]
If I use my old Mass Effect 2 DVDs to install the game and try to build a tree without adding any DLC, MassEffectModder will crash with an unhandled exception because it can't find 

Mass Effect 2\BioGame\DLC

This folder doesn't exist when you install just the game without DLCs from the original DVDs. It's different when you install the game from Steam.

As soon as you add one DLC to create the folder, MEM won't crash.

addendum 1: 
If the v1.37 build crashes due to a corrupt file within the game, it doesn't show which file was responsible. I think this feature is a must, and should be added again.

Especially the Zaeed-DLC from the Bioware-Shop is, for some unknown reason, prone to produce corrupt files. After my initial problems with this DLC, I installed it 10 times - and 3 times, it showed one or more corrupt files (each time different ones). And, yes, I re-downloaded the DLC to hash it again - something is off with this one DLC; every other one installs fine, no matter how often I repeat the process.

addendum 2:
It would be nice if you could see the name of the mem that was installed last. If you have a series of mems in one folder, it's otherwise easy to miss one or install one double.

**Comment by Thommaal** [comment]
One more observation: 
It's not an issue per se, but MEM doesn't recognize a new DLC on its own. I think, it would be a good idea if either the program checked for newly added DLCs and warned the user about the changes, or if there was a built-in way to delete the old tree. At the very least, MEM should tell a user where to find the trees, so that they can be deleted manually more swiftly (and not every user knows how to look for such files).

In case you wonder why anyone would build more than one tree in sequence before adding textures .. well, a user might simply have forgottten to add a DLC and remembered it after creating a tree. 

In my case, I use MEM to verify the installation of the DLC files. If MEM produces a tree without a crash, I delete the tree and add a couple more DLCs. :)

**Comment by aquadran** [comment]
Finally some bug! :) I'll add check for missing DLC, I dind't know such version exists.
Regarding 1: I'll restore this, at least for scan for now. I'm not sure if to restore for texture replacement again. But I'll think of it.
2: It's not issue if you add the same MEM again. Btw, you can add all to the list then install them in one batch. By selected them all and apply.

adding new DLC require rescan data. MEM would have to detect if game is not altered, since scan require vanilla data.
Regarding deleting tree map, I want add menu option to delete file. So user not need to find it and manually delete it.
But idea for detecting DLC changes is not bad. I need to figure out how to aprouch this. things might be more complicated with ME3.

Regarding data corruption, I have idea to data hash checks, MEM will know list of hashes for game data and will able to compare.

Anyway thanks for feedback! Any your are welcome if you have some ideas for improvements or new features.

**Comment by aquadran** [comment]
Can you try 1.38 version?

**Comment by Thommaal** [comment]
Wow, you're quick - I had just started to test it with v1.38 when I saw a new version already on the page :).

It works with v1.39 and v1.41. The issue is resolved and can be closed. Let's see if we find something else ;)

But, seriously, it's a great tool; and I'm about to test it more extensively with ME3.

**Comment by Thommaal** [comment]
Wait a moment, please. There is one more circumstance that might need attention, not an issue per se, but it could become a problem once MassEffect Modder will be used by a larger player pool:

LOD generation.

When I generate LODS and try to use the new gamersettings.ini with an older file that had different LOD settings, the dreaded black tecture issue will appear.

Of course, thne more experienced users will know what might have caused the texture problem, but I'm pretty sure many players won't realize that they need to delete the generated LOD-entries in the gamersettings.ini to solve the problem.

I think, it would be a good idea to add a warning about the potential issue with older files, when new LODs are about to be created.

**Comment by Thommaal** [comment]
One more observation:
I always make new mems with a new version to see if the files start to differ. And with v1.41, the files do differ compared to v1.37.

From the ALOT Characters.7z; folder: NPCs (Asari,Quarian,Turian,Salarian...)

v1.37
NPCs (Asari,Quarian,Turian,Salarian...).mem
MD5: C20278A73F63538C60A697E3732332DB

v1.41
NPCs (Asari,Quarian,Turian,Salarian...).mem
MD5: 8024F60CD2DF7B842B00124A08C1BECA

The newer file is bigger, so does that mean that older mems should not be used with new versions of MassEffectModder?

**Comment by aquadran** [comment]
Regarding LOD settings, I'll put something there. Maybe even option to remove from settings too.

**Comment by aquadran** [comment]
Regarding different sizes of .mem files I'm suprised. There were any changes in this matter. Let me check.

**Comment by aquadran** [comment]
I just checked NPCs (Asari,Quarian,Turian,Salarian...) and the same size with the same exaclty content.
