### ISSUE TITLE
v.1.41 Unhandled exception: The directory name is invalid

### ISSUE THREAD

**Issue by Thommaal** [MassEffectModder/MassEffectModder#5]
Could you please check if it's possible at all to apply mems with v1.41? 

I had tested everything except the most important bit (bloody stupid of me). When I try to apply a mem, I get an unhandled exception in ME2 with the message:

The directory name is invalid.

v1.37 and v1.39 work like a charm.

It's quite possible that something is off on my end, since I also had the mem-size issue with a few files while using v1.41 .. - v1.37 and v1.39 produce exactly the same files all the time.

**Comment by aquadran** [comment]
try 1.42

**Comment by aquadran** [comment]
Regarding mem-size issue on your end, try unpack and compare number of them.

**Comment by Thommaal** [comment]
v1.42 works fine; isue solved. 

Regarding the mem-issue: yes, of course, the file sizes correspond to the number of files within.

Garrus.mem, for example, included just 17 files when I created it with v1.37 - but there are 19 files within the ALOT-folder; and all of them are present and accounted for with v.14x.

The old armor.mem, otoh, includes 3 more files; but they produce errors: 

![armor-mem-old](https://cloud.githubusercontent.com/assets/24566859/21948154/91378394-d9e9-11e6-82e0-ab4d3c2b6216.png)

**Comment by Thommaal** [comment]
PS: I think I was stupid; the mem-issue is likely linked to differences in a full ME2-origin and an ME2-Steam installation. I'm going to check it out.

**Comment by Thommaal** [comment]
**All-clear signal: no issue at all with mem-creation!**

The differences in file numbers within the mems were simply caused by differences in the me2-tree; I hadn't realized earlier that two tiny DLCs hadn't correctly installed in the Origin-DVD-ME2, while they were present in the Steam-installation (well, that's one of the dangers of parallel installations of the same software).

I have added them correctly to the Origin-DVD installation, and the created mems are consistent again in all MEM-versions. 

It might interest you that the DVD installation is identical to the Steam installation in all relevant folders. So, there should be no trouble for MEM as long as it doesn't mind where the ME2-folder is located.
