### ISSUE TITLE
Re-scan game data

### ISSUE THREAD

**Issue by Nellast1992** [MassEffectModder/MassEffectModder#6]
Hello @aquadran. Whem i tried to "Texture Explorer" in Mass Effect 3, it's "Detected removal game data files from last game data scan. It's required to re-scan vanilla gama data again". How i can do that?
![problem](https://cloud.githubusercontent.com/assets/25132015/21961973/f8ea8cb2-db28-11e6-8f30-53ecca07f450.png)

**Comment by aquadran** [comment]
To able rescan at this point without manual deleting file I fixed a tool to able continue to begin re-scan textures.
Uploaded 1.51 version.
Let me know if it works.

btw. You need follow proper order, first install all DLC mods then start using MEM.

**Comment by Nellast1992** [comment]
It works fine this time, thanks! Great job you did!
