### ISSUE TITLE
Update LOD Causes Black Textures. 

### ISSUE THREAD

**Issue by phazer-11** [MassEffectModder/MassEffectModder#7]
Updating LOD causes Black Textures/Shadows in Mass Effect 3,  Photo and Video Below. 
https://goo.gl/photos/1iXysSegCcgYNv6o7

​https://www.youtube.com/watch?v=ePWZrufzUn4

**Comment by aquadran** [comment]
Did you removed empty mipmaps from textures?

**Comment by phazer-11** [comment]
Yes

**Comment by aquadran** [comment]
Try run remove mipmaps again. This is definietely caused by this.
Updating LOD and remove mipmaps are connected together.

**Comment by Thommaal** [comment]
@phazer-11, your black textures are linked to empty mipmaps; while testing MEM, I deliberately induced this result on ME2 and ME3 using a plethora of textures, and it was always solved by removing those mipmaps.

Though, if it should not work for you, please, list the texture upgrades you used and add the hashes of the mems that were created.

**Comment by aquadran** [comment]
@phazer-11 any news?

**Comment by aquadran** [comment]
@phazer-11 do you still reproduce issue?

**Comment by ThaDPG** [comment]
What do you mean when you say remove mipmaps?  I am having this same issue with the black textures.

**Comment by aquadran** [comment]
this is old thread to different scenario becouse missing step not removing empty mipmaps step. This is no longer matter.

**Comment by phazer-11** [comment]
Yeah just able to reply been super busy, it was actually the version of MEM
I was using, despite it being labled stable. Things are fine now.
Now, I'm wondering if there's a method to have MEM ignore texture format
for mods like MEUITM which change pretty much all of the formats for
reasons such as keeping the aliasing down by using uncompressed textures.

**Comment by aquadran** [comment]
There was never confirmed issue with black textures with that version or any other.
Regarding MEUITM there is no real reason to ignore texture format.
Uncompressed textures will not help aliasing down. In MEUITM case they are waste disk space and RAM.

**Comment by aquadran** [comment]
Regarding changing format, exceptions are MEUITM lightmaps, indeed DXT1 make them less smooth gradient because less RGB resolution in DXT1. so in practice it's better not touch them at all. I can not do much about it. Changing format make other consequnces which I don't want to make. at least not MEM v1 (if ever).
