### ISSUE TITLE
Crash with exception(s)

### ISSUE THREAD

**Issue by Cerberus-Shepard** [MassEffectModder/MassEffectModder#8]
hi used this to mod ME 2 went like a dream easy to use and FAST!

now onto the issue  i started to use it to mod ME3(left it extracting DlC overnight since it as late) when i got up this morning i had an exception error so 
i restarted the program(meant to take a screen shot but accidentally hit enter which cleared the message)...after the program restarted  
i tried to explore textures BUT it informed me 
i need to extract DLC  
i attempt to do that and get a message that there is nothing to extract...

currently repairing ME3 install and will try again(will also post the exception if it happens again) 

bugger need to RE-DOWNLOAD ALL my DLC because of that error....

sometimes i really hate and despise computers....

**Comment by aquadran** [comment]
let me check first, I made some changes recently to DLC code. I'll let you know.

**Comment by Cerberus-Shepard** [comment]
DLC downloaded while i was out dlc unpacking went without  issue as did tree build and .mem creation currently installing .mem files  guess it was just a random glitch....

program is great really really fast compared ME explorer!

**Comment by aquadran** [comment]
I didn't find issue with unpacking. so I guess no issue here.

**Comment by Cerberus-Shepard** [comment]
must have been something local on my end i guess  

one "weird" issue if i select more than 4 of the .mem files generated from Alot ME3 it tells me i need 241GB free if i select ALL the .mem files it tells me i need 983GB free space....

**Comment by aquadran** [comment]
yes... :) I fixed this, I'll upload new version soon.

**Comment by aquadran** [comment]
I just uploaded fixed 1.56 version.
