### ISSUE TITLE
Texture Explorer - Tool Doesn't have Write Access to Game Data

### ISSUE THREAD

**Issue by Vand3rz** [MassEffectModder/MassEffectModder#9]
Windows 10

I've tried running as Administrator, turning off UAC, adding permission for everyone to write, it's outside of my C drive, unchecking read only just resets after closing properties.

Does anyone know what else I can try?

**Comment by aquadran** [comment]
Can you try 1.63 release?

**Comment by Vand3rz** [comment]
Oh yes I didn't realise there was a new release. It's fixed now thank you.

**Comment by aquadran** [comment]
There was not :) I just changed write access checks.
